In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from itertools import permutations
import pandas as pd
from random import random
%matplotlib notebook

In [ ]:
s_aco_ls = np.load("../IR33_S_ACO_ls.npz")
s_aco_normal = np.load("../IR33_S_ACO_normal.npz")

In [7]:
s_aco_ls.keys()

['costs',
 'sols',
 'times',
 'p_bi',
 'p_gi',
 'n_bi',
 'n_gi',
 'ls_num_improvements',
 'ls_rate_improvements',
 'glob_best_change',
 'diversity',
 'avg_time',
 'best_performances',
 'avg_performances',
 'best_robusteness',
 'avg_robusteness']

In [14]:
n_costs = s_aco_normal['costs']
print("{}, {}".format(type(n_costs), np.shape(n_costs)))
n_costs

<class 'numpy.ndarray'>, (10,)


array([79054.33494824, 81506.92897928, 79626.33506339, 79592.04925599,
       79385.86987304, 79430.07247094, 78883.10954754, 78124.04532781,
       81373.19089798, 79384.55763032])

In [12]:
n_sols = s_aco_normal['sols']
print("{}, {}".format(type(n_sols), np.shape(n_sols)))
n_sols

<class 'numpy.ndarray'>, (10, 232)


array([[202,  21, 101, ..., 177,  36,  97],
       [ 18, 208, 172, ..., 137, 177,   3],
       [ 84, 217,  17, ..., 107, 133, 205],
       ...,
       [203,  32,  29, ..., 100, 200,   7],
       [139, 192, 106, ..., 102, 117, 161],
       [ 15, 187, 114, ...,  68,  51, 223]])

In [13]:
n_times = s_aco_normal['times']
print("{}, {}".format(type(n_times), np.shape(n_times)))
n_times

<class 'numpy.ndarray'>, (10,)


array([60.68878269, 63.58511472, 61.93656373, 61.87520146, 61.0638783 ,
       60.5932653 , 63.25396037, 65.50279474, 64.18549657, 62.95331192])

In [15]:
n_p_bi = s_aco_normal['p_bi']
print("{}, {}".format(type(n_p_bi), np.shape(n_p_bi)))
n_p_bi

<class 'numpy.ndarray'>, (40, 1000)


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [18]:
n_n_bi = s_aco_normal['n_bi']
print("{}, {}".format(type(n_n_bi), np.shape(n_n_bi)))
n_n_bi

<class 'numpy.ndarray'>, (40, 1000)


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [19]:
n_ls_num = s_aco_normal['ls_num_improvements']
print("{}, {}".format(type(n_ls_num), np.shape(n_ls_num)))
n_ls_num

<class 'numpy.ndarray'>, (20,)


array([array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.,